server:
    port: 8801
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
service:
    security:
       secure-key-username: maik
       secure-key-password: maik13
spring:
    jpa:
        database: POSTGRESQL

        hibernate.ddl-auto: update
        show-sql: true
    datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.2.127:5432/product
        username: maik
        password: maik1310

logging:
    level:
        '[com.netflix.eureka]': 'OFF'
        '[com.netflix.discovery]': 'OFF'
