server:
    port: 0
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://192.168.2.127:8761/eureka}
    instance:
        instance-id: ${spring.application.name}:${random.uuid}

service:
    security:
       secure-key-username: maik
       secure-key-password: maik13
spring:
    application:
        name: product-ms-db
    datasource:
        #driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.2.127:5432/product
        username: maik
        password: maik1310
